<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MedicamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicamentos = [
            // ANALGÉSICOS
            [
                'codigo_medicamento' => 'MED-ANAL-001',
                'nombre_comercial' => 'Paracetamol',
                'nombre_generico' => 'Acetaminofén',
                'principio_activo' => 'Paracetamol',
                'laboratorio' => 'Farma S.A.',
                'presentacion' => 'Tableta',
                'concentracion' => '500mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANALGESICO,
                'es_controlado' => false,
                'precio_unitario' => 1.50,
                'indicaciones' => 'Analgésico y antipirético para dolor leve a moderado y fiebre',
                'contraindicaciones' => 'Hipersensibilidad al paracetamol, insuficiencia hepática grave',
                'efectos_adversos' => 'Raros: rash cutáneo, hepatotoxicidad en dosis altas',
                'dosis_maxima_24h' => 4000,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ANAL-002',
                'nombre_comercial' => 'Morfina',
                'nombre_generico' => 'Sulfato de morfina',
                'principio_activo' => 'Morfina',
                'laboratorio' => 'Pfizer',
                'presentacion' => 'Ampolleta',
                'concentracion' => '10mg/ml',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::INTRAVENOSA,
                'categoria' => \App\Enums\CategoriaMedicamento::ANALGESICO,
                'es_controlado' => true,
                'precio_unitario' => 25.00,
                'indicaciones' => 'Analgésico opioide para dolor severo',
                'contraindicaciones' => 'Depresión respiratoria, asma bronquial aguda',
                'efectos_adversos' => 'Sedación, náuseas, estreñimiento, dependencia',
                'dosis_maxima_24h' => 100,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ANAL-003',
                'nombre_comercial' => 'Tramadol',
                'nombre_generico' => 'Tramadol clorhidrato',
                'principio_activo' => 'Tramadol',
                'laboratorio' => 'Grunenthal',
                'presentacion' => 'Cápsula',
                'concentracion' => '50mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANALGESICO,
                'es_controlado' => true,
                'precio_unitario' => 3.50,
                'indicaciones' => 'Dolor moderado a severo',
                'contraindicaciones' => 'Epilepsia no controlada, intoxicación alcohólica',
                'efectos_adversos' => 'Mareos, náuseas, somnolencia',
                'dosis_maxima_24h' => 400,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],

            // ANTIBIÓTICOS
            [
                'codigo_medicamento' => 'MED-ANTIB-001',
                'nombre_comercial' => 'Amoxicilina',
                'nombre_generico' => 'Amoxicilina',
                'principio_activo' => 'Amoxicilina trihidratada',
                'laboratorio' => 'GSK',
                'presentacion' => 'Cápsula',
                'concentracion' => '500mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANTIBIOTICO,
                'es_controlado' => false,
                'precio_unitario' => 2.00,
                'indicaciones' => 'Infecciones bacterianas susceptibles',
                'contraindicaciones' => 'Hipersensibilidad a penicilinas',
                'efectos_adversos' => 'Diarrea, náuseas, rash alérgico',
                'dosis_maxima_24h' => 3000,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ANTIB-002',
                'nombre_comercial' => 'Ciprofloxacino',
                'nombre_generico' => 'Ciprofloxacino',
                'principio_activo' => 'Ciprofloxacino clorhidrato',
                'laboratorio' => 'Bayer',
                'presentacion' => 'Tableta',
                'concentracion' => '500mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANTIBIOTICO,
                'es_controlado' => false,
                'precio_unitario' => 4.50,
                'indicaciones' => 'Infecciones del tracto urinario, respiratorio',
                'contraindicaciones' => 'Niños menores de 18 años, embarazo',
                'efectos_adversos' => 'Náuseas, diarrea, tendinitis',
                'dosis_maxima_24h' => 1500,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ANTIB-003',
                'nombre_comercial' => 'Ceftriaxona',
                'nombre_generico' => 'Ceftriaxona sódica',
                'principio_activo' => 'Ceftriaxona',
                'laboratorio' => 'Roche',
                'presentacion' => 'Vial',
                'concentracion' => '1g',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::INTRAVENOSA,
                'categoria' => \App\Enums\CategoriaMedicamento::ANTIBIOTICO,
                'es_controlado' => false,
                'precio_unitario' => 15.00,
                'indicaciones' => 'Infecciones graves por gérmenes susceptibles',
                'contraindicaciones' => 'Hipersensibilidad a cefalosporinas',
                'efectos_adversos' => 'Dolor en sitio de inyección, diarrea',
                'dosis_maxima_24h' => 4000,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => true,
                'activo' => true,
            ],

            // ANTIINFLAMATORIOS
            [
                'codigo_medicamento' => 'MED-ANTINF-001',
                'nombre_comercial' => 'Ibuprofeno',
                'nombre_generico' => 'Ibuprofeno',
                'principio_activo' => 'Ibuprofeno',
                'laboratorio' => 'Novartis',
                'presentacion' => 'Tableta',
                'concentracion' => '400mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANTIINFLAMATORIO,
                'es_controlado' => false,
                'precio_unitario' => 1.80,
                'indicaciones' => 'Dolor, inflamación, fiebre',
                'contraindicaciones' => 'Úlcera péptica activa, insuficiencia renal grave',
                'efectos_adversos' => 'Dispepsia, náuseas, úlceras gastrointestinales',
                'dosis_maxima_24h' => 2400,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ANTINF-002',
                'nombre_comercial' => 'Diclofenaco',
                'nombre_generico' => 'Diclofenaco sódico',
                'principio_activo' => 'Diclofenaco',
                'laboratorio' => 'Voltaren',
                'presentacion' => 'Tableta',
                'concentracion' => '50mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ANTIINFLAMATORIO,
                'es_controlado' => false,
                'precio_unitario' => 2.20,
                'indicaciones' => 'Artritis, dolor musculoesquelético',
                'contraindicaciones' => 'Úlcera péptica, enfermedad cardiovascular',
                'efectos_adversos' => 'Molestias gastrointestinales, mareos',
                'dosis_maxima_24h' => 150,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],

            // CARDIOVASCULARES
            [
                'codigo_medicamento' => 'MED-CARDIO-001',
                'nombre_comercial' => 'Enalapril',
                'nombre_generico' => 'Enalapril maleato',
                'principio_activo' => 'Enalapril',
                'laboratorio' => 'Merck',
                'presentacion' => 'Tableta',
                'concentracion' => '10mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::CARDIOVASCULAR,
                'es_controlado' => false,
                'precio_unitario' => 1.20,
                'indicaciones' => 'Hipertensión arterial, insuficiencia cardíaca',
                'contraindicaciones' => 'Embarazo, estenosis bilateral de arteria renal',
                'efectos_adversos' => 'Tos seca, hipotensión, mareos',
                'dosis_maxima_24h' => 40,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-CARDIO-002',
                'nombre_comercial' => 'Atorvastatina',
                'nombre_generico' => 'Atorvastatina cálcica',
                'principio_activo' => 'Atorvastatina',
                'laboratorio' => 'Lipitor',
                'presentacion' => 'Tableta',
                'concentracion' => '20mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::CARDIOVASCULAR,
                'es_controlado' => false,
                'precio_unitario' => 3.00,
                'indicaciones' => 'Hipercolesterolemia, prevención cardiovascular',
                'contraindicaciones' => 'Enfermedad hepática activa, embarazo',
                'efectos_adversos' => 'Mialgia, elevación de transaminasas',
                'dosis_maxima_24h' => 80,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],

            // GASTROINTESTINALES
            [
                'codigo_medicamento' => 'MED-GASTRO-001',
                'nombre_comercial' => 'Omeprazol',
                'nombre_generico' => 'Omeprazol',
                'principio_activo' => 'Omeprazol',
                'laboratorio' => 'AstraZeneca',
                'presentacion' => 'Cápsula',
                'concentracion' => '20mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::GASTROINTESTINAL,
                'es_controlado' => false,
                'precio_unitario' => 1.50,
                'indicaciones' => 'Úlcera péptica, reflujo gastroesofágico',
                'contraindicaciones' => 'Hipersensibilidad al omeprazol',
                'efectos_adversos' => 'Cefalea, diarrea, náuseas',
                'dosis_maxima_24h' => 40,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],

            // RESPIRATORIOS
            [
                'codigo_medicamento' => 'MED-RESP-001',
                'nombre_comercial' => 'Salbutamol',
                'nombre_generico' => 'Salbutamol sulfato',
                'principio_activo' => 'Salbutamol',
                'laboratorio' => 'GSK',
                'presentacion' => 'Inhalador',
                'concentracion' => '100mcg/dosis',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::INHALATORIA,
                'categoria' => \App\Enums\CategoriaMedicamento::RESPIRATORIO,
                'es_controlado' => false,
                'precio_unitario' => 12.00,
                'indicaciones' => 'Broncoespasmo, asma, EPOC',
                'contraindicaciones' => 'Hipersensibilidad al salbutamol',
                'efectos_adversos' => 'Temblor, taquicardia, nerviosismo',
                'dosis_maxima_24h' => 800,
                'unidad_dosis_maxima' => 'mcg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],

            // ENDOCRINOS
            [
                'codigo_medicamento' => 'MED-ENDO-001',
                'nombre_comercial' => 'Insulina NPH',
                'nombre_generico' => 'Insulina humana NPH',
                'principio_activo' => 'Insulina',
                'laboratorio' => 'Novo Nordisk',
                'presentacion' => 'Vial',
                'concentracion' => '100UI/ml',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::SUBCUTANEA,
                'categoria' => \App\Enums\CategoriaMedicamento::ENDOCRINO,
                'es_controlado' => false,
                'precio_unitario' => 35.00,
                'indicaciones' => 'Diabetes mellitus tipo 1 y 2',
                'contraindicaciones' => 'Hipoglucemia',
                'efectos_adversos' => 'Hipoglucemia, lipodistrofia',
                'dosis_maxima_24h' => 100,
                'unidad_dosis_maxima' => 'UI',
                'requiere_refrigeracion' => true,
                'activo' => true,
            ],
            [
                'codigo_medicamento' => 'MED-ENDO-002',
                'nombre_comercial' => 'Metformina',
                'nombre_generico' => 'Metformina clorhidrato',
                'principio_activo' => 'Metformina',
                'laboratorio' => 'Bristol Myers',
                'presentacion' => 'Tableta',
                'concentracion' => '850mg',
                'via_administracion' => \App\Enums\ViaAdministracionMedicamento::ORAL,
                'categoria' => \App\Enums\CategoriaMedicamento::ENDOCRINO,
                'es_controlado' => false,
                'precio_unitario' => 1.00,
                'indicaciones' => 'Diabetes mellitus tipo 2',
                'contraindicaciones' => 'Insuficiencia renal, acidosis metabólica',
                'efectos_adversos' => 'Diarrea, náuseas, sabor metálico',
                'dosis_maxima_24h' => 2550,
                'unidad_dosis_maxima' => 'mg',
                'requiere_refrigeracion' => false,
                'activo' => true,
            ],
        ];

        foreach ($medicamentos as $medicamento) {
            \App\Models\Medicamento::create($medicamento);
        }

        $this->command->info('✅ Se crearon ' . count($medicamentos) . ' medicamentos');
    }
}
